### ISSUE TITLE
ModuleNotFoundError: No module named 'core.settings.local'

### ISSUE THREAD

**Issue by ghost** [dansackett/django-project-template#1]
[In This Section](https://github.com/dansackett/django-project-template/blob/master/core/settings/__init__.py) i got ModuleNotFoundError

Error Log:
```
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/batuhan/catchAPI/django-project-template/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/batuhan/catchAPI/django-project-template/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/home/batuhan/catchAPI/django-project-template/.venv/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/batuhan/catchAPI/django-project-template/.venv/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/batuhan/catchAPI/django-project-template/.venv/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/batuhan/catchAPI/django-project-template/core/settings/__init__.py", line 2, in <module>
    from .local import *
ModuleNotFoundError: No module named 'core.settings.local'
```

**Comment by louzhang** [comment]
Hi any update on this? I am running into the same error. Thanks!

**Comment by dansackett** [comment]
@louiszhang97 let me first say that this repo is very old and I wouldn't really recommend it today since I last updated it in 2017. That said, the issue you're seeing is because you don't have a file called `core/settings/local.py`. This file is in the `.gitignore` so it is not tracked in version control. It allows you to setup your database settings, debug settings, etc. It would expect this file to be the base: https://github.com/dansackett/django-project-template/blob/master/core/settings/local.example.py.
